# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0b191205dfad3c6290cae3743a5dfe67533c0a253871bbc81066fa8c25d7ab361e2619bc2b8bb4333e0ab1f24c450889eb920a1ff6a3403e6c16b0912a3cd141

test:
  secret_key_base: ff8c5d945d1c49c8cd360cc6590a615dd159c710e683ca57d54e144394b8a4f95b40973a8d9fcd556c5950047e20e4ed249fa02fe50378417ef5fae864db3eac

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  secret_key_base: 0b191205dfad3c6290cae3743a5dfe67533c0a253871bbc81066fa8c25d7ab361e2619bc2b8bb4333e0ab1f24c450889eb920a1ff6a3403e6c16b0912a3cd141